### ISSUE TITLE
Issue with header "application/json"

### ISSUE THREAD

**Issue by code-rgb** [DragSama/tracemoepy#2]
**Code:**
```
import tracemoepy
tracemoe = tracemoepy.async_trace.Async_Trace()
```

**Error:**

```
Traceback (most recent call last):
  File "/app/userge/plugins/tools/executor.py", line 75, in eval_
    ret_val = await aexec(cmd)
  File "/app/userge/plugins/tools/executor.py", line 72, in aexec
    return await locals()["__aexec"](userge, message)
  File "<string>", line 3, in __aexec
  File "/app/.heroku/python/lib/python3.8/site-packages/tracemoepy/async_trace.py", line 20, in __init__
    self.aio_session.headers = {"Content-Type": "application/json"}
AttributeError: can't set attribute
```

**Comment by code-rgb** [comment]
**This Issue because of Aiohttp so closing issue**
  locking `aiohttp==3.6.3` did the trick.

**Comment by code-rgb** [comment]
The default content type http header for json is "application/json"
but I'm getting [this error](https://del.dog/myluperfyv ) instead.

**sending the post request** [without headers is working fine ](https://del.dog/raw/upeckocyno)
`aiohttp==3.7.3`

**Comment by DragSama** [comment]
Can you try using `pip install git+https://github.com/DragSama/tracemoepy/` and then try search/natural_preview again ?

**Comment by code-rgb** [comment]
👍🏻 Both are working fine now, you can close this issue.
