### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by Nksama** [DragSama/tracemoepy#8]
Running setup.py install for brotlipy ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-vcg1z530\\brotlipy_45075a6a828b42edb345b9eb65f2e134\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-vcg1z530\\brotlipy_45075a6a828b42edb345b9eb65f2e134\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\HP\AppData\Local\Temp\pip-record-zf394yby\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\HP\AppData\Roaming\Python\Python39\Include\brotlipy'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-vcg1z530\brotlipy_45075a6a828b42edb345b9eb65f2e134\
    Complete output (12 lines):
    running install
    running build
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\brotli
    copying src\brotli\brotli.py -> build\lib.win-amd64-3.9\brotli
    copying src\brotli\build.py -> build\lib.win-amd64-3.9\brotli
    copying src\brotli\__init__.py -> build\lib.win-amd64-3.9\brotli
    running build_clib
    building 'libbrotli' library
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-vcg1z530\\brotlipy_45075a6a828b42edb345b9eb65f2e134\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-vcg1z530\\brotlipy_45075a6a828b42edb345b9eb65f2e134\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\HP\AppData\Local\Temp\pip-record-zf394yby\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\HP\AppData\Roaming\Python\Python39\Include\brotlipy' Check the logs for full command output.

**Comment by DragSama** [comment]
The error message already explains how to fix it:
`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/` (Also check [stackoverflow](https://www.google.com/search?q=pip+install+requires+visual+c%2B%2B+site:stackoverflow.com))

**Comment by Nksama** [comment]
> 
> 
> The error message already explains how to fix it:
> `error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/` (Also check [stackoverflow](https://www.google.com/search?q=pip+install+requires+visual+c%2B%2B+site:stackoverflow.com))

**Comment by Nksama** [comment]
k
